export const game_vocab = {  
    animals:{
        cat:{english: 'cat', swedish: 'en katt', article: 'en', sv: 'katt', definition: 'a small animal with fur, usually kept as a pet or for catching mice', clue: 'has four legs, wields a tail and meows when necessary'},
        dog:{english: 'dog',  swedish: 'en hund', article: 'en', sv: 'hund', definition: 'a domestic pet with four legs, kept by people as a pet or to guard things', clue: 'barks on you, licks your face and likes to sleep in your bed'},
        fox:{english: 'fox',  swedish: 'en räv', article: 'en', sv: 'räv', definition: 'a wild animal with pointed ears and a reddish-brown fur', clue: 'has a wide tail and likes to hunt your chickens'},
        sheep:{english: 'sheep',  swedish: 'en får', article: 'ett', sv: 'får', definition: 'a farm animal with thick wool', clue: 'eats grass and is herded by dogs'},
        giraffe:{english: 'giraffe',  swedish: 'en giraff', article: 'en', sv: 'giraff', definition: 'a large African animal with very long neck', clue: 'is yellow in colour and has brown spots'},
        crocodile:{english: 'crocodile',  swedish: 'en krokodil',article: 'en', sv: 'krokodil', definition: 'a large reptile with hard skin that lives near the rivers', clue: 'like an alligator, but has a longer nose'},
        peacock:{english: 'peacock',  swedish: 'en påfågel',article: 'en', sv: 'påfågel', definition: 'a large bird, the male of which has a very long colourful tail feathers', clue: 'the pattern of the feathers is shaped like eyes'},
    },
    weekdays:{
        Monday:{english: 'Monday', article: 'en', sv: 'måndag', definition: 'the day of the week after Sunday and before Tuesday', clue: 'first day of the week'},
        Tuesday:{english: 'Tuesday', article: 'en', sv: 'tisdag', definition: 'the day of the week after Monday and before Wednesday', clue: 'second day of the week'},
        Wednesday:{english: 'Wednesday', article: 'en', sv: 'onsdag', definition: 'the day of the week after Tuesday and before Thursday', clue: 'third day of the week'},
        Thursday:{english: 'Thursday', article: 'en', sv: 'tirsdag', definition: 'the day of the week after Wednesday and before Friday', clue: 'fourth day of the week'},
        Friday:{english: 'Friday', article: 'en', sv: 'fredag', definition: 'the day of the week after Thursday and before Saturday', clue: 'fifth day of the week'},
        Saturday:{english: 'Saturday', article: 'en', sv: 'lördag', definition: 'the day of the week after Friday and before Sunday', clue: 'sixth day of the week'},
        Sunday:{english: 'Sunday', article: 'en', sv: 'söndag', definition: 'the day of the week after Saturday and before Monday', clue: 'seventh day of the week'},
    },
    occupation:{
        teacher:{english: 'teacher', article: 'en', sv: 'lärare', definition: 'someone whose job is to teach in a school or college', clue: 'a person who instructs or trains others on subjects like chemistry and biology, especially in a school'},
        doctor:{english: 'doctor', article: 'en', sv: 'läkare', definition: 'a person with a medical degree whose job is to treat people who are ill or hurt', clue: 'they work in hospitals'},
        builder:{english: 'builder', article: 'en', sv: 'byggare', definition: 'a person whose job it is to make buildings', clue: 'a cartoon character: Bob the...'},
        lifeguard:{english: 'lifeguard', article: 'en', sv: 'badvakt', definition: 'a person on a beach or at a swimming pool whose job is to make certain that the swimmers are safe', clue: 'usually wears red swimsuits on duty'},
        actor:{english: 'actor', article: 'en', sv: 'skådespelare', definition: 'someone who pretends to be someone else while performing', clue: 'works in films, plays, television or radio programmes'},
        engineer:{english: 'enginerr', article: 'en', sv: 'ingengör', definition: 'a person whose job is to design or build machines, engines or other equipment', clue: 'occupation which requires physics, mathematics and IT knowledge'},
        garbage_man:{english: 'garbage man', article: 'en', sv: 'sopgubbe', definition: "a person whose job is to empty people's dustbins and take the rubbish away", clue: 'they come with a garbage truck'},
    },
    colours:{
        yellow:{english: 'yellow', sv: 'gul', definition: 'the colour like that of a lemon or gold or the sun', clue: 'you get orange when you mix this colour with red'},
        red:{english: 'red', sv: 'röd', definition: 'the colour of fresh blood', clue: 'one of the primary colours'},
        purple:{english: 'purple', sv: 'lila', definition: 'the dark reddish-blue colour', clue: 'the colour under your eyes'},
        brown:{english: 'brown', sv: 'brun', definition: 'the colour of chocolate or soil', clue: 'a common colour for hair'},
        black:{english: 'black', sv: 'svart', definition: 'the colour of coal or a very dark night', clue: 'the darkest colour there is'},
        white:{english: 'white', sv: 'vit', definition: 'the colour like that of snow, milk, or bone', clue: 'the lightest colour there is'},
        green:{english: 'green', sv: 'grön', definition: 'the colour of grass', clue: 'the colour between blue and yellow'},
    },
    verbs:{
        go:{english: 'go', sv: 'gå', definition: 'move to another place on foot', clue: 'another word for walk'},
        run:{english: 'run', sv: 'springa', definition: 'go on foot but fast', clue: 'the action of each foot lifting before the next foot touches the ground'},
        eat:{english: 'eat', sv: 'äta', definition: 'to put food into the mouth', clue: 'favourite activity of the day besides sleeping'},
        sleep:{english: 'sleep', sv: 'sova', definition: 'to be in the state of rest when your eyes are closed and your body is not active', clue: 'to be in  the state of the body when you dream'},
        write:{english: 'write', sv: 'skriva', definition: 'to make marks that represent letters, words, or numbers on a surface, such as paper or a computer screen', clue: 'a pencil, pen or a keyboard is required'},
        sing:{english: 'sing', sv: 'sjunga', definition: 'to make musical sound with the voice', clue: 'favourite activity in the shower'},
        drink:{english: 'drink', sv: 'dricka', definition: 'to take liquid into the body through the mouth', clue: 'consume water and other liquids'},
    },
    family:{
        cousin:{english: 'cousin', article: 'en', sv: 'kusin', definition: "a child of a person's aunt or uncle", clue: 'a hairy character from TV series Addams Family: Itt'},
        brother:{english: 'brother', article: 'en', sv: 'bror', definition: 'a man or boy with the same parents as another person', clue: 'the opposite of a sister'},
        sister:{english: 'sister', article: 'en', sv: 'syster', definition: 'a girl or woman who has the same parents as another person', clue: 'the opposite of a brother'},
        mum:{english: 'mum', article: 'en', sv: 'mamma', definition: 'the female parent', clue: 'the opposite of dad'},
        dad:{english: 'dad', article: 'en', sv: 'pappa', definition: 'the male parent', clue: 'the opposite of mum'},
        grandma_1:{english: "grandma from your mother's side", article: 'en', sv: 'mormor', definition: 'mother of your mother', clue: 'the opposite of grandpa'},
        grandma_2:{english: "grandma from your father's side", article: 'en', sv: 'farmor', definition: 'mother of your father', clue: 'the opposite of grandpa'},
    },
    geographical:{
        river:{english: 'river', article: 'en', sv: 'flod', definition: 'a natural wide flow of fresh water across the land', clue: 'Amazon and Nile'},
        mountain:{english: 'mountain', article: 'ett', sv: 'berg', definition: "a raised part of the earth's surface, much larger than a hill", clue: 'Fuji and Kebnekaise'},
        sea:{english: 'sea', article: 'ett', sv: 'hav', definition: 'the salty water that covers a large part of the surface of the earth, smaller than an ocean', clue: 'Baltic and Caspian'},
        forest:{english: 'forest', article: 'en', sv: 'skog', definition: 'a large area of land covered with trees and plants', clue: 'Amazon, Siberian'},
        lake:{english: 'lake', article: 'en', sv: 'sjö', definition: 'a large area of water surrounded by land and not connected to the sea', clue: 'Baikal, Loch Ness'},
        cliff:{english: 'cliff', article: 'en', sv: 'klippa', definition: 'a high area of rock with a very steep side, often on a coast', clue: 'Trolltunga'},
        cave:{english: 'cave', article: 'en', sv: 'grotta', definition: 'a large hole in the side of a hill, cliff, or mountain, or one that is underground', clue: 'Lascaux'},
    }
    }
